cluster:
  name: CLUSTER_NAME
path:
  data: /data
  logs: /home/admin/logs  
node:
  name: NODE_NAME
network:
  host: NODE_IP
discovery:
  zen.ping.unicast.hosts: [CLUSTER_IPS]
  zen.minimum_master_nodes: ZEN_NUM
indices: 
  requests.cache.size: 2%
index:
  store.type: niofs